version: '3.8'
name: infra_elk
services:
  elk_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elk_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:UseSVE=0
      - CLI_JAVA_OPTS=-XX:UseSVE=0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elk_data:/usr/share/elasticsearch/data
    networks:
      - elk

  elk_logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: elk_logstash
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    volumes:
      - ./config/elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./config/elk/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    depends_on:
      - elk_elasticsearch
    networks:
      - elk

  elk_kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: elk_kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elk_elasticsearch:9200
    depends_on:
      - elk_elasticsearch
    networks:
      - elk

volumes:
  elk_data:

networks:
  elk:
    driver: bridge
      