version: '3.8'
services:
  web:
    build: .
    ports:
      - "4567:4567"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db/auth_service
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_service
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
