default: &default
  host: localhost
  user: postgres
  password: postgres
  adapter: postgres

development:
  <<: *default
  db: users_development

test:
  <<: *default
  db: users_test

production:
  <<: *default
  db: users_production
