name: Admins service integration tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: users
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Install Python dependencies
      run: |
        cd admins.py
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start server
      run: |
        cd admins.py
        nohup python app.py &
        sleep 5

    - name: Wait for server to be ready
      run: |
        timeout 10 bash -c 'until echo > /dev/tcp/localhost/5001; do sleep 1; done'

    - name: Install Ruby dependencies
      run: |
        cd admins.test
        gem install bundler
        bundle install

    - name: Run tests
      run: |
        cd admins.test
        rspec
